# Generated by Django 2.2.5 on 2020-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='title',
            field=models.CharField(default='New thread', max_length=500),
        ),
    ]
