# Generated by Django 2.2.5 on 2020-05-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_discussionthread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='posted_under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
