# Generated by Django 2.2.5 on 2020-05-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_discussionthread_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='topic',
        ),
    ]
