# Generated by Django 2.2.5 on 2020-05-05 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_discussionthread_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadresponse',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.DiscussionThread'),
        ),
        migrations.AlterField(
            model_name='threadresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
