# Generated by Django 2.2.5 on 2020-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_rounds',
            field=models.IntegerField(),
        ),
    ]
