# Generated by Django 2.2.5 on 2020-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200512_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='completed_rounds',
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
